// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzoyjciyywdxshizoygh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6b3lqY2l5eXdkeHNoaXpveWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjQ2MDQsImV4cCI6MjA3MjE0MDYwNH0.kv_fbAIIETfFWH-9XT7FD1ErQ-5JuZ0gzEajvN1u9wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});